In [41]:
import numpy as np



In [86]:
scale_factor = 12
file_name = "5C_1_1.pcd"

f = open(file_name, mode="r+")

data = f.read()

data = data.split("\n")

header_data = data[:10]

points = []

for x in data[11:]:
    points.append(x.split("\t"))

# points.remove([''])

f_points = []
for x in points:
    # print(x)
    f_points.append([float(x[0]), float(x[1]), float(x[2])])

f_points = np.asarray(f_points)

f_points = np.divide(f_points, scale_factor)
    

print(f_points)

new_data = ""

for x in f_points:
    new_data = new_data + str(x[0]) + "\t" +str(x[1]) + "\t" + str(x[2]) + "\n"



f2 = open("new_test.pcd", "w+")

print(len(f_points))
f2.seek(0)
for x in data[:10]:
    f2.write(x)
    f2.write("\n")

for i in new_data:
    f2.write(i)

f2.close()


[[ 0.02083296 -0.04166667  0.02189976]
 [-0.01866268 -0.04166667  0.01390837]
 [-0.04140559 -0.04166667 -0.03026161]
 ...
 [ 0.05962449 -0.04147189 -0.04166667]
 [ 0.12384034 -0.04088637 -0.04166667]
 [ 0.10845278  0.00674149 -0.04166667]]
1682


In [118]:
scale_factor = 15
file_name = "5C_2_3_2000.txt"

f = open(file_name, mode="r+")

data = f.read()

data = data.split("\n")

points = []

for x in data[1:]:
    points.append(x.split(" "))

# print(points)
points.remove([''])

f_points = []
for x in points:
    # print(x)
    f_points.append([float(x[0]), float(x[1]), float(x[2])])




f_points = np.asarray(f_points)

f_points = np.divide(f_points, scale_factor)
    
sigma = 0.005

f_points += np.random.normal(0,sigma, f_points.shape)




print(f_points)

new_data = ""

for x in f_points:
    new_data = new_data + str(x[0]) + "\t" +str(x[1]) + "\t" + str(x[2]) + "\n"



f2 = open("new_test.pcd", "w+")

print(len(f_points))
f2.seek(0)
for x in header_data:
    f2.write(x)
    f2.write("\n")

for i in new_data:
    f2.write(i)

f2.close()

[[-0.02936633  0.01344978  0.00499636]
 [-0.02615589  0.02702236 -0.0065423 ]
 [-0.04266225 -0.00313385 -0.02052713]
 ...
 [ 0.09268288  0.0027585   0.16851926]
 [ 0.09182683  0.00830917  0.1600052 ]
 [ 0.06715947  0.00751853  0.16842506]]
20003
